// Lookup tables keyed by canonical Productsoort strings.
// Edit values here to adjust groupings — no logic changes needed.
// Deprecated / merged product types live in the alias table below, not here.

export const PRODUCTSOORT_TO_ARTIKELGROEP: Record<string, string> = {
  'Accessoires':              'Kleding',
  'Amerikaanse Overal':       'Kleding',
  'Bodybroek':                'Kleding',
  'Bodywarmers':              'Kleding',
  'Bretelbroeken':            'Kleding',
  'Colberts':                 'Kleding',
  'Fleece Jack':              'Kleding',
  'Fleece Vest':              'Kleding',
  'Fleecevest':               'Kleding',
  'Gehoorbescherming':        'Gehoorbescherming',
  'Halfgelaatsmasker':        'Adembescherming',
  'Handschoenen':             'Werkhandschoenen',
  'Helmen':                   'Veiligheidshelmen',
  'Hoody Sweater':            'Kleding',
  'Inlegzolen':               'Schoeisel',
  'Jassen':                   'Kleding',
  'Klompen':                  'Schoeisel',
  'Kniestukken':              'Kleding',
  'Korte broeken':            'Kleding',
  'Laarzen':                  'Schoeisel',
  'Muilen':                   'Schoeisel',
  'Mutsen':                   'Kleding',
  'Ondergoed':                'Kleding',
  'Otoplastieken':            'Gehoorbescherming',
  'Overalls':                 'Kleding',
  'Overhemden':               'Kleding',
  'Overige artikelen':        'Kleding',
  'Pantalons':                'Kleding',
  'Piraatbroeken':            'Kleding',
  'Poloshirt':                'Kleding',
  'Poloshirt Extra Lang':     'Kleding',
  'Polosweater':              'Kleding',
  'Regenkleding':             'Kleding',
  'Reparatiesets Schoeisel':  'Schoeisel',
  'Riemen':                   'Kleding',
  'Rokken':                   'Kleding',
  'Schorten':                 'Kleding',
  'Shorts':                   'Kleding',
  'Slippers/Sandalen':        'Schoeisel',
  'Sokken':                   'Kleding',
  'Spijkerbroeken':           'Kleding',
  'Stedmanen':                'Kleding',
  'Stofjas':                  'Kleding',
  'Stofmaskers':              'Adembescherming',
  'Sweaters':                 'Kleding',
  'Sweatshirts':              'Kleding',
  'Thermokleding':            'Kleding',
  'Trainingsbroek':           'Kleding',
  'Truien':                   'Kleding',
  'T-shirts':                 'Kleding',
  'T-shirts Extra Lang':      'Kleding',
  'Tuinbroeken':              'Kleding',
  'Veiligheidsbrillen':       'Veiligheidsbrillen',
  'Veiligheidshesje':         'Kleding',
  'Veiligheidsschoenen':      'Schoeisel',
  'Vesten':                   'Kleding',
  'Veters':                   'Kleding',
  'Voering':                  'Kleding',
  'Waadpak':                  'Kleding',
  'Wandelschoenen':           'Schoeisel',
  'Werkbroeken':              'Kleding',
  'Werklaars':                'Schoeisel',
  'Werkschoen Hoog':          'Schoeisel',
  'Werkschoen Instapper':     'Schoeisel',
  'Werkschoen Laag':          'Schoeisel',
};

export const PRODUCTSOORT_TO_EENHEID: Record<string, string> = {
  'Accessoires':              'Stuks',
  'Amerikaanse Overal':       'Stuks',
  'Bodybroek':                'Stuks',
  'Bodywarmers':              'Stuks',
  'Bretelbroeken':            'Stuks',
  'Colberts':                 'Stuks',
  'Fleece Jack':              'Stuks',
  'Fleece Vest':              'Stuks',
  'Fleecevest':               'Stuks',
  'Gehoorbescherming':        'Stuks',
  'Halfgelaatsmasker':        'Stuks',
  'Handschoenen':             'Paar',
  'Helmen':                   'Stuks',
  'Hoody Sweater':            'Stuks',
  'Inlegzolen':               'Paar',
  'Jassen':                   'Stuks',
  'Klompen':                  'Paar',
  'Kniestukken':              'Stuks',
  'Korte broeken':            'Stuks',
  'Laarzen':                  'Paar',
  'Muilen':                   'Paar',
  'Mutsen':                   'Stuks',
  'Ondergoed':                'Stuks',
  'Otoplastieken':            'Paar',
  'Overalls':                 'Stuks',
  'Overhemden':               'Stuks',
  'Overige artikelen':        'Stuks',
  'Pantalons':                'Stuks',
  'Piraatbroeken':            'Stuks',
  'Poloshirt':                'Stuks',
  'Poloshirt Extra Lang':     'Stuks',
  'Polosweater':              'Stuks',
  'Regenkleding':             'Stuks',
  'Reparatiesets Schoeisel':  'Paar',
  'Riemen':                   'Stuks',
  'Rokken':                   'Stuks',
  'Schorten':                 'Stuks',
  'Shorts':                   'Stuks',
  'Slippers/Sandalen':        'Paar',
  'Sokken':                   'Stuks',
  'Spijkerbroeken':           'Stuks',
  'Stedmanen':                'Stuks',
  'Stofjas':                  'Stuks',
  'Stofmaskers':              'Stuks',
  'Sweaters':                 'Stuks',
  'Sweatshirts':              'Stuks',
  'Thermokleding':            'Stuks',
  'Trainingsbroek':           'Stuks',
  'Truien':                   'Stuks',
  'T-shirts':                 'Stuks',
  'T-shirts Extra Lang':      'Stuks',
  'Tuinbroeken':              'Stuks',
  'Veiligheidsbrillen':       'Stuks',
  'Veiligheidshesje':         'Stuks',
  'Veiligheidsschoenen':      'Paar',
  'Vesten':                   'Stuks',
  'Veters':                   'Paar',
  'Voering':                  'Stuks',
  'Waadpak':                  'Stuks',
  'Wandelschoenen':           'Paar',
  'Werkbroeken':              'Stuks',
  'Werklaars':                'Paar',
  'Werkschoen Hoog':          'Paar',
  'Werkschoen Instapper':     'Paar',
  'Werkschoen Laag':          'Paar',
};

export const DEFAULT_ARTIKELGROEP = 'Kleding';
export const DEFAULT_EENHEID = 'Stuks';

/**
 * Alias table: non-canonical names → their canonical Dutch Productsoort key.
 * Covers English, German, French, and deprecated/merged Dutch terms.
 * Values MUST be keys in PRODUCTSOORT_TO_ARTIKELGROEP.
 */
export const ENGLISH_TO_DUTCH_PRODUCTSOORT: Record<string, string> = {
  // ── English ───────────────────────────────────────────────
  // A
  'Accessories':              'Accessoires',
  'American Overall':         'Amerikaanse Overal',
  'Apron':                    'Schorten',
  'Aprons':                   'Schorten',
  // B
  'Bag':                      'Sweaters',
  'Bags':                     'Sweaters',
  'Base Layer':               'Ondergoed',
  'Beanie':                   'Mutsen',
  'Beanies':                  'Mutsen',
  'Belt':                     'Riemen',
  'Belts':                    'Riemen',
  'Bib & Brace':              'Bretelbroeken',
  'Bib and Brace':            'Bretelbroeken',
  'Bib Trousers':             'Bretelbroeken',
  'Body Trousers':            'Bodybroek',
  'Body Warmer':              'Bodywarmers',
  'Body Warmers':             'Bodywarmers',
  'Bodywarmer':               'Bodywarmers',
  'Boot':                     'Laarzen',
  'Boots':                    'Laarzen',
  'Bump Cap':                 'Helmen',
  // C
  'Cap':                      'Mutsen',
  'Caps':                     'Mutsen',
  'Capri Trousers':           'Piraatbroeken',
  'Cargo Pants':              'Werkbroeken',
  'Cargo Trousers':           'Werkbroeken',
  'Clogs':                    'Klompen',
  'Clog':                     'Klompen',
  'Coat':                     'Jassen',
  'Coats':                    'Jassen',
  'Coverall':                 'Overalls',
  'Coveralls':                'Overalls',
  'Custom Ear Protection':    'Otoplastieken',
  // D
  'Denim Trousers':           'Spijkerbroeken',
  'Dress Trousers':           'Pantalons',
  'Dungaree':                 'Tuinbroeken',
  'Dungarees':                'Tuinbroeken',
  'Dust Coat':                'Stofjas',
  'Dust Mask':                'Stofmaskers',
  'Dust Masks':               'Stofmaskers',
  // E
  'Ear Defenders':            'Gehoorbescherming',
  'Ear Plugs':                'Gehoorbescherming',
  'Ear Protection':           'Gehoorbescherming',
  'Earmuffs':                 'Gehoorbescherming',
  'Earplugs':                 'Gehoorbescherming',
  'Extra Long Polo Shirt':    'Poloshirt Extra Lang',
  'Extra Long T-Shirts':      'T-shirts Extra Lang',
  'Extra Long T-shirts':      'T-shirts Extra Lang',
  'Eye Protection':           'Veiligheidsbrillen',
  // F
  'Face Mask':                'Stofmaskers',
  'Face Masks':               'Stofmaskers',
  'Fleece Jacket':            'Fleece Jack',
  // G
  'Glove':                    'Handschoenen',
  'Gloves':                   'Handschoenen',
  // H
  'Half Face Mask':           'Halfgelaatsmasker',
  'Half Face Respirator':     'Halfgelaatsmasker',
  'Hand Protection':          'Handschoenen',
  'Hard Hat':                 'Helmen',
  'Hard Hats':                'Helmen',
  'Hat':                      'Mutsen',
  'Hats':                     'Mutsen',
  'Head Protection':          'Helmen',
  'Hearing Protection':       'Gehoorbescherming',
  'Helmet':                   'Helmen',
  'Helmets':                  'Helmen',
  'Hi Vis':                   'Veiligheidshesje',
  'Hi Vis Vest':              'Veiligheidshesje',
  'Hi-Vis Vest':              'Veiligheidshesje',
  'High Safety Shoe':         'Werkschoen Hoog',
  'High Visibility':          'Veiligheidshesje',
  'High Visibility Jacket':   'Regenkleding',
  'High Visibility Vest':     'Veiligheidshesje',
  'High Work Shoe':           'Werkschoen Hoog',
  'High-Vis Vest':            'Veiligheidshesje',
  'High-Visibility Vest':     'Veiligheidshesje',
  'Hiking Boots':             'Wandelschoenen',
  'Hiking Shoes':             'Wandelschoenen',
  'Hooded Sweater':           'Hoody Sweater',
  'Hoodie':                   'Hoody Sweater',
  'Hoody':                    'Hoody Sweater',
  // I
  'Insole':                   'Inlegzolen',
  'Insoles':                  'Inlegzolen',
  // J
  'Jacket':                   'Jassen',
  'Jackets':                  'Jassen',
  'Jeans':                    'Spijkerbroeken',
  'Joggers':                  'Trainingsbroek',
  'Jumper':                   'Truien',
  'Jumpers':                  'Truien',
  // K
  'Knee Pad':                 'Kniestukken',
  'Knee Pads':                'Kniestukken',
  'Knee Protection':          'Kniestukken',
  'Kneepad':                  'Kniestukken',
  'Kneepads':                 'Kniestukken',
  // L
  'Lab Coat':                 'Stofjas',
  'Lace':                     'Veters',
  'Laces':                    'Veters',
  'Lining':                   'Voering',
  'Low Safety Shoe':          'Werkschoen Laag',
  'Low Work Shoe':            'Werkschoen Laag',
  // M
  'Miscellaneous':            'Overige artikelen',
  'Mule':                     'Muilen',
  'Mules':                    'Muilen',
  // N
  'Noise Protection':         'Gehoorbescherming',
  // O
  'Other Articles':           'Overige artikelen',
  'Otoplastics':              'Otoplastieken',
  'Overall':                  'Overalls',
  // P
  'Pants':                    'Werkbroeken',
  'Pirate Trousers':          'Piraatbroeken',
  'Polo Shirt':               'Poloshirt',
  'Polo Sweater':             'Polosweater',
  'Protective Eyewear':       'Veiligheidsbrillen',
  'Protective Glasses':       'Veiligheidsbrillen',
  'Pullover':                 'Truien',
  'Pullovers':                'Truien',
  // R
  'Rain Coat':                'Regenkleding',
  'Rain Gear':                'Regenkleding',
  'Rain Jacket':              'Regenkleding',
  'Rain Pants':               'Regenkleding',
  'Rain Trousers':            'Regenkleding',
  'Raincoat':                 'Regenkleding',
  'Rainwear':                 'Regenkleding',
  'Reflective Vest':          'Veiligheidshesje',
  'Respirator':               'Halfgelaatsmasker',
  'Respirator Mask':          'Adembescherming',
  // S
  'Safety Boot':              'Werklaars',
  'Safety Boots':             'Werklaars',
  'Safety Footwear':          'Veiligheidsschoenen',
  'Safety Glasses':           'Veiligheidsbrillen',
  'Safety Goggles':           'Veiligheidsbrillen',
  'Safety Helmet':            'Veiligheidshelmen',
  'Safety Helmets':           'Veiligheidshelmen',
  'Safety Shoe':              'Veiligheidsschoenen',
  'Safety Shoes':             'Veiligheidsschoenen',
  'Safety Spectacles':        'Veiligheidsbrillen',
  'Safety Vest':              'Veiligheidshesje',
  'Sandals':                  'Slippers/Sandalen',
  'Shirt':                    'Overhemden',
  'Shirts':                   'T-shirts',
  'Shoe Repair Kit':          'Reparatiesets Schoeisel',
  'Shoe Repair Kits':         'Reparatiesets Schoeisel',
  'Shoelace':                 'Veters',
  'Shoelaces':                'Veters',
  'Short Trousers':           'Korte broeken',
  'Skirt':                    'Rokken',
  'Skirts':                   'Rokken',
  'Sleeveless Overall':       'Amerikaanse Overal',
  'Sleeveless Overalls':      'Amerikaanse Overal',
  'Slip-on Shoes':            'Muilen',
  'Slip-on Work Shoe':        'Werkschoen Instapper',
  'Slippers':                 'Slippers/Sandalen',
  'Sock':                     'Sokken',
  'Socks':                    'Sokken',
  'Suspender Trousers':       'Bretelbroeken',
  'Sweatpants':               'Trainingsbroek',
  // T
  'T-Shirt':                  'T-shirts',
  'Tee Shirt':                'T-shirts',
  'Thermal':                  'Thermokleding',
  'Thermal Clothing':         'Thermokleding',
  'Thermals':                 'Thermokleding',
  'Training Trousers':        'Trainingsbroek',
  'Trouser':                  'Werkbroeken',
  'Trousers':                 'Werkbroeken',
  // W
  'Waders':                   'Waadpak',
  'Wading Suit':              'Waadpak',
  'Waistcoat':                'Vesten',
  'Waistcoats':               'Vesten',
  'Walking Shoes':            'Wandelschoenen',
  'Waterproof Jacket':        'Regenkleding',
  'Waterproof Pants':         'Regenkleding',
  'Waterproof Trousers':      'Regenkleding',
  'Work Boot':                'Werklaars',
  'Work Boots':               'Werklaars',
  'Work Gloves':              'Handschoenen',
  'Work Jeans':               'Spijkerbroeken',
  'Work Pants':               'Werkbroeken',
  'Work Shirt':               'Overhemden',
  'Work Shirts':              'Overhemden',
  'Work Trousers':            'Werkbroeken',
  'Worker Jeans':             'Spijkerbroeken',

  // ── German ───────────────────────────────────────────────
  'Arbeitshandschuhe':        'Handschoenen',
  'Arbeitshosen':             'Werkbroeken',
  'Arbeitsschuhe':            'Veiligheidsschoenen',
  'Arbeitsstiefel':           'Werklaars',
  'Atemschutz':               'Adembescherming',
  'Bundhosen':                'Werkbroeken',
  'Einlegesohle':             'Inlegzolen',
  'Einlegesohlen':            'Inlegzolen',
  'Fleecejacke':              'Fleece Jack',
  'Fleeceweste':              'Fleecevest',
  'Gehörschutz':              'Gehoorbescherming',
  'Halbmaske':                'Halfgelaatsmasker',
  'Handschuhe':               'Handschoenen',
  'Hosen':                    'Werkbroeken',
  'Jacke':                    'Jassen',
  'Jacken':                   'Jassen',
  'Knieprotektoren':          'Kniestukken',
  'Knieschutz':               'Kniestukken',
  'Knieschützer':             'Kniestukken',
  'Latzhosen':                'Bretelbroeken',
  'Mütze':                    'Mutsen',
  'Mützen':                   'Mutsen',
  'Regenhose':                'Regenkleding',
  'Regenjacke':               'Regenkleding',
  'Regenanzug':               'Regenkleding',
  'Schürze':                  'Schorten',
  'Schürzen':                 'Schorten',
  'Schutzbrille':             'Veiligheidsbrillen',
  'Schutzbrillen':            'Veiligheidsbrillen',
  'Schutzhandschuhe':         'Handschoenen',
  'Schutzhelm':               'Helmen',
  'Schutzhelme':              'Helmen',
  'Schnürsenkel':             'Veters',
  'Sicherheitshelm':          'Veiligheidshelmen',
  'Sicherheitsschuhe':        'Veiligheidsschoenen',
  'Sicherheitsstiefel':       'Werklaars',
  'Sicherheitsweste':         'Veiligheidshesje',
  'Socken':                   'Sokken',
  'Staubmaske':               'Stofmaskers',
  'Stiefel':                  'Laarzen',
  'Warnweste':                'Veiligheidshesje',
  'Warnwesten':               'Veiligheidshesje',
  'Weste':                    'Vesten',

  // ── French ───────────────────────────────────────────────
  'Bottes de sécurité':       'Werklaars',
  'Casque':                   'Helmen',
  'Casques':                  'Helmen',
  'Chaussettes':              'Sokken',
  'Chaussures de sécurité':   'Veiligheidsschoenen',
  'Combinaison':              'Overalls',
  'Gant':                     'Handschoenen',
  'Gants':                    'Handschoenen',
  'Gilet':                    'Veiligheidshesje',
  'Lunettes de protection':   'Veiligheidsbrillen',
  'Lunettes de sécurité':     'Veiligheidsbrillen',
  'Masque':                   'Stofmaskers',
  'Pantalon':                 'Werkbroeken',
  'Tablier':                  'Schorten',
  'Veste':                    'Jassen',

  // ── Deprecated Dutch terms (merged into canonical names above) ────────────
  'Bodywarmers/Werkvesten':   'Bodywarmers',
  'Broeken':                  'Werkbroeken',
  'Fleece':                   'Fleece Jack',
  'Jeans Casual':             'Spijkerbroeken',
  'Jeans Worker':             'Spijkerbroeken',
  'Mouwlozeoveralls':         'Amerikaanse Overal',
  'Polo':                     'Poloshirt',
  'Polos':                    'Poloshirt',
  'Sweater':                  'Sweaters',
  'Underwear':                'Ondergoed',
  'Veiligheidsvest':          'Veiligheidshesje',
  'Vests':                    'Vesten',
  'Tassen':                   'Sweaters',
};

export const ARTIKELGROEP_OPTIONS: string[] = [
  'Adembescherming',
  'Gehoorbescherming',
  'Kleding',
  'Schoeisel',
  'Veiligheidsbrillen',
  'Veiligheidshelmen',
  'Werkhandschoenen',
];
